stages:
  - tests

tests:
  image: 'python:3.11.7-bullseye'
  stage: tests

  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install --upgrade wheel setuptools pip
    - pip install cython
    - python3 -m pip install --upgrade pip
    - pip install -r requirements.txt
    - coverage run --source=. -m pytest
    - coverage report
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  only:
    - master
    - main
    - merge_requests
